
import sys

path = r'C:\Users\thesh\Downloads\BTL-nhom24-main - Copy\BTL-nhom24-main\src\frontend\gui\schedule_gui.py'
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

start_line = -1
end_line = -1
for i, line in enumerate(lines):
    if 'def _refresh(self):' in line:
        start_line = i
    if 'for i in range(6): self._grid_frame.rowconfigure' in line:
        end_line = i

if start_line != -1 and end_line != -1:
    new_method = [
        '    def _refresh(self):\n',
        '        self._update_week_label()\n',
        '        for w in self._grid_frame.winfo_children():\n',
        '            w.destroy()\n',
        '        \n',
        '        room_filter = self._v_room.get()\n',
        '        only_mine = self._only_mine.get()\n',
        '        user_id = self.current_user.user_id if only_mine else ""\n',
        '        \n',
        '        schedule_rows = self.booking_ctrl.build_schedule(self._week_offset, only_user_id=user_id) # type: ignore\n',
        '\n',
        '        today = dt.date.today()\n',
        '        mon, _ = self.booking_ctrl.week_date_range(self._week_offset) # type: ignore\n',
        '\n',
        '        # Stats counters\n',
        '        total_bookings = 0\n',
        '        stats = {"Da duyet": 0, "Cho duyet": 0, "Tu choi": 0}\n',
        '\n',
        '        grid_data: dict[tuple[int, str], list[tuple[str, str, str]]] = {}\n',
        '        for row in schedule_rows:\n',
        '            if room_filter != "Tat ca phong" and row.room_id != room_filter:\n',
        '                continue\n',
        '            \n',
        '            if row.status in stats:\n',
        '                stats[row.status] += 1\n',
        '                total_bookings += 1\n',
        '            \n',
        '            try:\n',
        '                day_idx = self.DAYS.index(row.weekday)\n',
        '                grid_data.setdefault((day_idx, row.slot), []).append(\n',
        '                    (row.label, row.status, row.room_id)\n',
        '                )\n',
        '            except ValueError:\n',
        '                continue\n',
        '\n',
        '        # Draw Grid\n',
        '        for d_idx in range(7):\n',
        '            d_date = mon + dt.timedelta(days=d_idx)\n',
        '            d_str  = d_date.strftime("%d/%m")\n',
        '            is_today = (d_date == today)\n',
        '            \n',
        '            bg_h = "#f1f5f9" if not is_today else "#eef2ff"\n',
        '            fg_h = "#64748b" if not is_today else "#4f46e5"\n',
        '            h = tk.Frame(self._grid_frame, bg=bg_h, padx=4, pady=10, highlightthickness=1, highlightbackground="#e2e8f0")\n',
        '            h.grid(row=0, column=d_idx+1, sticky="nsew")\n',
        '            tk.Label(h, text=self.DAYS[d_idx], bg=bg_h, fg=fg_h, font=("Segoe UI", 9, "bold")).pack()\n',
        '            tk.Label(h, text=d_str, bg=bg_h, fg=fg_h, font=("Segoe UI", 8)).pack()\n',
        '\n',
        '            for s_idx, s_key in enumerate(self.SLOT_KEYS):\n',
        '                entries = grid_data.get((d_idx, s_key), [])\n',
        '                cell = tk.Frame(self._grid_frame, bg="#ffffff", highlightthickness=1, highlightbackground="#e2e8f0")\n',
        '                cell.grid(row=s_idx+1, column=d_idx+1, sticky="nsew")\n',
        '\n',
        '                if entries:\n',
        '                    _, status, _ = entries[0]\n',
        '                    bg, fg = CELL_COLORS.get(status, ("#f1f5f9", "#475569"))\n',
        '                    \n',
        '                    inner = tk.Frame(cell, bg=bg, cursor="hand2")\n',
        '                    inner.pack(fill="both", expand=True, padx=2, pady=2)\n',
        '                    \n',
        '                    if status in CELL_ACCENT:\n',
        '                        tk.Frame(inner, bg=CELL_ACCENT[status], width=4).pack(side="left", fill="y")\n',
        '                    \n',
        '                    txt = f"{len(entries)} lich" if len(entries) > 1 else entries[0][0]\n',
        '                    if len(txt) > 22: txt = txt[:20] + ".."\n',
        '                    \n',
        '                    lbl = tk.Label(inner, text=txt, bg=bg, fg=fg, font=("Segoe UI", 8, "bold"), pady=4)\n',
        '                    lbl.pack(fill="both", expand=True)\n',
        '\n',
        '                    _cell_tooltip(lbl, [(e[0], e[1]) for e in entries], d_date.isoformat(), s_key)\n',
        '                    \n',
        '                    for w in (inner, lbl):\n',
        '                        w.bind("<Button-1>", lambda e, ents=entries, ds=d_date.isoformat(), \n',
        '                                                dn=self.DAYS[d_idx], sl=self.SLOTS_LBL[s_idx]:\n',
        '                                                self._show_cell_detail(ents, ds, dn, sl))\n',
        '                else:\n',
        '                    pass\n',
        '\n',
        '        # Update Stats Bar\n',
        '        for w in self._stats_bar.winfo_children():\n',
        '            w.destroy()\n',
        '\n',
        '        busy_cells = sum(1 for v in grid_data.values() if v)\n',
        '        total_cells = 7 * 5\n',
        '        rate = int(busy_cells * 100 / total_cells) if total_cells else 0\n',
        '\n',
        '        header_f = tk.Frame(self._stats_bar, bg="#1e1b4b", padx=16, pady=8)\n',
        '        header_f.pack(fill="x")\n',
        '        tk.Label(header_f, text="📊 Thong ke tuan nay", bg="#1e1b4b", fg="#e0e7ff", font=("Segoe UI", 10, "bold")).pack(side="left")\n',
        '\n',
        '        chips_f = tk.Frame(self._stats_bar, bg="#ffffff", padx=14, pady=12)\n',
        '        chips_f.pack(fill="both", expand=True)\n',
        '\n',
        '        def _stat_chip(parent, icon, label, value, fg, bar_color=None):\n',
        '            chip = tk.Frame(parent, bg="#f8fafc", highlightthickness=1, highlightbackground="#e2e8f0", padx=15, pady=10)\n',
        '            chip.pack(side="left", padx=6)\n',
        '            tk.Label(chip, text=f"{icon} {value}", bg="#f8fafc", fg=fg, font=("Segoe UI", 16, "bold")).pack(anchor="w")\n',
        '            tk.Label(chip, text=label, bg="#f8fafc", fg="#64748b", font=("Segoe UI", 9)).pack(anchor="w")\n',
        '            if bar_color and total_bookings > 0:\n',
        '                tk.Frame(chip, bg="#e2e8f0", height=3).pack(fill="x", pady=(4,0))\n',
        '\n',
        '        _stat_chip(chips_f, "📅", "Tong so lich", str(total_bookings), "#4f46e5")\n',
        '        _stat_chip(chips_f, "✅", "Da duyet", str(stats["Da duyet"]), "#15803d")\n',
        '        _stat_chip(chips_f, "⏳", "Cho duyet", str(stats["Cho duyet"]), "#b45309")\n',
        '        _stat_chip(chips_f, "❌", "Tu choi", str(stats["Tu choi"]), "#db2777")\n',
        '        _stat_chip(chips_f, "📈", "Ty le su dung", f"{rate}%", "#0369a1")\n',
        '\n',
        '        for i in range(8): self._grid_frame.columnconfigure(i, weight=1, uniform="eq")\n',
        '        for i in range(6): self._grid_frame.rowconfigure(i, weight=1, uniform="eq")\n'
    ]
    
    final_lines = lines[:start_line] + new_method + lines[end_line+1:]
    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(final_lines)
